image: tari/tihle-build:latest

stages:
  - build
  - test
  - package
  - deploy


.cargo:
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo_home
  cache:
    paths:
    - .cargo_home/bin
    - .cargo_home/registry/index
    - .cargo_home/registry/cache
    - .cargo_home/git/db
    - target/


test:
  stage: test
  needs: []
  script:
  - cargo test --locked


build:windows:
  stage: build
  needs: []
  extends: .cargo
  cache:
    key: windows-release
  variables:
    # Cross-compiling for mingw and exception handling is rather fraught:
    # https://github.com/rust-lang/rust/issues/32859
    CARGO_TARGET_I686_PC_WINDOWS_GNU_LINKER: "i686-w64-mingw32-gcc"
    CARGO_TARGET_I686_PC_WINDOWS_GNU_RUSTFLAGS: "-Cpanic=abort -Clink-args=icon.res.o"
  script:
    # Link in resources so we have a nice icon
    - i686-w64-mingw32-windres dist/icon.rc icon.res.o
    # Ask sdl2 to statically link against an SDL library it provides for us
    - cargo build --bins --release --locked --target=i686-pc-windows-gnu --features=sdl2/static-link,sdl2/bundled
  artifacts:
    paths:
    - target/i686-pc-windows-gnu/release/


build:emscripten:
  stage: build
  needs: []
  extends: .cargo
  cache:
    key: emscripten-release
  script:
    - make -C programs
    - mkdir -p out/programs
    - cp programs/*.8xp out/programs/
    - cargo build --bins --release --locked --target=wasm32-unknown-emscripten
  artifacts:
    paths:
      - programs/
      - target/wasm32-unknown-emscripten/release/


package:emscripten:
  stage: package
  needs: ["build:emscripten"]
  script:
    - ./dist/build-web.sh
  artifacts:
    paths:
      - out/web/


pages:
  stage: deploy
  needs: ["package:emscripten"]
  only: [master]
  script:
    - mv out/web public
  artifacts:
    paths:
      - public/


build:linux:
  stage: build
  needs: []
  extends: .cargo
  cache:
    key: linux-release
  script:
    - cargo build --bins --release --locked --target=x86_64-unknown-linux-gnu --features=sdl2/static-link,sdl2/bundled
  artifacts:
    paths:
      - target/x86_64-unknown-linux-gnu/release/


package:linux:
  stage: package
  needs: ["build:linux"]
  script:
    - ./dist/build-appimage.sh
  artifacts:
    paths:
      - tihle-*-x86_64.AppImage
