image: tari/tihle-build:latest

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo_home

cache:
  key: cargo
  paths:
  - .cargo_home/bin
  - .cargo_home/registry/index
  - .cargo_home/registry/cache
  - .cargo_home/git/db

stages:
- test
- release


test:
  script:
  - cargo test --locked


build-emscripten:
  stage: release
  script:
  - cargo build --bins --release --locked --target=wasm32-unknown-emscripten
  artifacts:
    paths:
    - target/wasm32-unknown-emscripten/release/


build-windows:
  stage: release
  variables:
    # Cross-compiling for mingw and exception handling is rather fraught:
    # https://github.com/rust-lang/rust/issues/32859
    CARGO_TARGET_I686_PC_WINDOWS_GNU_LINKER: "i686-w64-mingw32-gcc"
    CARGO_TARGET_I686_PC_WINDOWS_GNU_RUSTFLAGS: "-Cpanic=abort"
  script:
  # Ask sdl2 to statically link against an SDL library it provides for us
  - cargo build --bins --release --locked --target=i686-pc-windows-gnu --features=sdl2/static-link,sdl2/bundled
  artifacts:
    paths:
    - target/i686-pc-windows-gnu/release/
